### ISSUE TITLE
Run py using your original raw code without any amendment

### ISSUE THREAD

**Issue by cheechochoy** [fermanjj/multiprocessing-and-multithreading-Python-example#2]
Hi Ferman,
Tried to understand how your code works. Appreciate if you can let me know what could have caused this error. TQ!

Traceback (most recent call last):
  File "C:\Users\cc_ch\PycharmProjects\vorMonitoring\testanimation.py", line 86, in <module>
    start_processes()
  File "C:\Users\cc_ch\PycharmProjects\vorMonitoring\testanimation.py", line 80, in start_processes
    p.start()
  File "C:\Users\cc_ch\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\cc_ch\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\cc_ch\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\Users\cc_ch\AppData\Local\Programs\Python\Python310\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\cc_ch\AppData\Local\Programs\Python\Python310\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread.lock' object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\cc_ch\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\cc_ch\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by fermanjj** [comment]
@cheechochoy I wrote this code 6+ years ago. I was probably still running Python 2.7 at the time. If you want, you're welcome to take a stab at updating it. Unfortunately at this point, I don't see the worth for me in updating this as it's not used by anyone and it's really just here as some starter example code.

It looks like based on this issue and the one from #1 that something changed with the way multiprocessing is done in Python 3.
